### ISSUE TITLE
Changing the input field URL php-fpm status

### ISSUE THREAD

**Issue by click0** [Busindre/PHP-FPM-status-Cacti#3]
Please add a field value, do not leave it blank.

![screenshot-10 0 0 21-2018-07-25-18-54-29](https://user-images.githubusercontent.com/396824/43212351-68064a86-903c-11e8-9284-ea1236d14a5d.png)

```
		<data>
			<item_000>
				<data_input_field_id>hash_070025b50e3b80b286db0c0ed47f7049690ec3</data_input_field_id>
				<t_value>on</t_value>
				<value>url</value>
			</item_000>
		</data>
```

**Comment by Busindre** [comment]
I'm sorry, can you do the modification? I have not used Cacti for a long time, it would be better if you collaborate and bring the change you need.
